version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: meet-the-music
    volumes:
      - data-postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  data-postgres:
