version: '3.8'
services:
  postgres:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - data-postgres:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'

volumes:
  data-postgres:
