import { MigrationInterface, QueryRunner } from 'typeorm';
import { User } from '../../users/entities/user.entity';
import { EstablishmentProfile } from '../../establishment-profile/entities/establishment-profile.entity';
import { Status } from '../../users/enums/status.enum';
import { Role } from '../../users/enums/role.enum';
import { EstablishmentType } from '../../establishment-profile/enums/establishment-type.enum';

export class SeedingCreateEstablishment1716889701262
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const fakeEstablishments = [
      {
        alias: 'jeremy-cafe',
        email: 'jeremy-cafe54@mail.fr',
        firstName: 'Jeremy',
        lastName: 'Cafe',
        description:
          "Restaurant avec une cuisine traditionnelle et des produits locaux de qualité. Avec haute capacité d'accueil",
        capacity: 230,
        address: '12 rue des écoles',
        phone: '0123456789',
        zipCode: '69001',
        city: 'Lyon 1er',
        role: Role.PROMOTER,
        status: Status.ACTIVE,
        isVerifyEmail: true,
        name: 'Jeremy Café',
        website: 'https://jeremy-cafe.fr',
        establishmentType: EstablishmentType.RESTAURANT,
        retaurantAddress: '12 rue des écoles',
        restaurantPhone: '0123456789',
        restaurantEmail: 'cafe.jeremy@mail.fr',
      },
      {
        alias: 'sophie-bar',
        email: 'sophie-bar@mail.fr',
        firstName: 'Sophie',
        lastName: 'Bar',
        description:
          'Bar convivial avec une grande sélection de bières artisanales et une ambiance chaleureuse.',
        capacity: 120,
        address: '15 avenue des Champs',
        phone: '0234567890',
        zipCode: '75008',
        city: 'Paris',
        role: Role.PROMOTER,
        status: Status.ACTIVE,
        isVerifyEmail: true,
        name: 'Sophie Bar',
        website: 'https://sophie-bar.fr',
        establishmentType: EstablishmentType.BAR,
        retaurantAddress: '15 avenue des Champs',
        restaurantPhone: '0234567890',
        restaurantEmail: 'bar.sophie@mail.fr',
      },
      {
        alias: 'paul-club',
        email: 'paul-club@mail.fr',
        firstName: 'Paul',
        lastName: 'Club',
        description:
          'Club branché avec des DJ sets chaque week-end et une piste de danse spacieuse.',
        capacity: 300,
        address: '20 rue de la Soirée',
        phone: '0345678901',
        zipCode: '75011',
        city: 'Paris',
        role: Role.PROMOTER,
        status: Status.ACTIVE,
        isVerifyEmail: true,
        name: 'Paul Club',
        website: 'https://paul-club.fr',
        establishmentType: EstablishmentType.CLUB,
        retaurantAddress: '20 rue de la Soirée',
        restaurantPhone: '0345678901',
        restaurantEmail: 'club.paul@mail.fr',
      },
      {
        alias: 'marie-pub',
        email: 'marie-pub@mail.fr',
        firstName: 'Marie',
        lastName: 'Pub',
        description:
          'Pub avec une ambiance anglaise authentique, des matchs de sport en direct et une grande variété de bières.',
        capacity: 180,
        address: '5 rue de Londres',
        phone: '0456789012',
        zipCode: '69002',
        city: 'Lyon 2e',
        role: Role.PROMOTER,
        status: Status.ACTIVE,
        isVerifyEmail: true,
        name: 'Marie Pub',
        website: 'https://marie-pub.fr',
        establishmentType: EstablishmentType.PUB,
        retaurantAddress: '5 rue de Londres',
        restaurantPhone: '0456789012',
        restaurantEmail: 'pub.marie@mail.fr',
      },
      {
        alias: 'emma-lounge',
        email: 'emma-lounge@mail.fr',
        firstName: 'Emma',
        lastName: 'Lounge',
        description:
          'Lounge moderne avec des cocktails créatifs, une ambiance cosy et des sièges confortables.',
        capacity: 100,
        address: '30 boulevard des Amis',
        phone: '0567890123',
        zipCode: '75015',
        city: 'Paris',
        role: Role.PROMOTER,
        status: Status.ACTIVE,
        isVerifyEmail: true,
        name: 'Emma Lounge',
        website: 'https://emma-lounge.fr',
        establishmentType: EstablishmentType.LOUNGE,
        retaurantAddress: '30 boulevard des Amis',
        restaurantPhone: '0567890123',
        restaurantEmail: 'lounge.emma@mail.fr',
      },
      {
        alias: 'julien-cafe',
        email: 'julien-cafe@mail.fr',
        firstName: 'Julien',
        lastName: 'Cafe',
        description:
          'Café branché avec une ambiance décontractée, parfait pour des réunions informelles et des petits-déjeuners.',
        capacity: 80,
        address: '25 rue des Cafés',
        phone: '0678901234',
        zipCode: '75010',
        city: 'Paris',
        role: Role.PROMOTER,
        status: Status.ACTIVE,
        isVerifyEmail: true,
        name: 'Julien Café',
        website: 'https://julien-cafe.fr',
        establishmentType: EstablishmentType.CAFE,
        retaurantAddress: '25 rue des Cafés',
        restaurantPhone: '0678901234',
        restaurantEmail: 'cafe.julien@mail.fr',
      },
      {
        alias: 'claire-restaurant',
        email: 'claire-restaurant@mail.fr',
        firstName: 'Claire',
        lastName: 'Restaurant',
        description:
          'Restaurant gastronomique avec des plats raffinés et un service exceptionnel.',
        capacity: 150,
        address: '10 rue de la Cuisine',
        phone: '0789012345',
        zipCode: '75004',
        city: 'Paris',
        role: Role.PROMOTER,
        status: Status.ACTIVE,
        isVerifyEmail: true,
        name: 'Claire Restaurant',
        website: 'https://claire-restaurant.fr',
        establishmentType: EstablishmentType.RESTAURANT,
        retaurantAddress: '10 rue de la Cuisine',
        restaurantPhone: '0789012345',
        restaurantEmail: 'restaurant.claire@mail.fr',
      },
      {
        alias: 'nicolas-bar',
        email: 'nicolas-bar@mail.fr',
        firstName: 'Nicolas',
        lastName: 'Bar',
        description:
          'Bar à cocktails avec une ambiance chic et des boissons innovantes.',
        capacity: 110,
        address: '18 rue des Verres',
        phone: '0890123456',
        zipCode: '69003',
        city: 'Lyon 3e',
        role: Role.PROMOTER,
        status: Status.ACTIVE,
        isVerifyEmail: true,
        name: 'Nicolas Bar',
        website: 'https://nicolas-bar.fr',
        establishmentType: EstablishmentType.BAR,
        retaurantAddress: '18 rue des Verres',
        restaurantPhone: '0890123456',
        restaurantEmail: 'bar.nicolas@mail.fr',
      },
      {
        alias: 'sophie-club',
        email: 'sophie-club@mail.fr',
        firstName: 'Sophie',
        lastName: 'Club',
        description:
          'Club de nuit avec une ambiance électrique et des soirées à thème chaque semaine.',
        capacity: 250,
        address: '22 rue de la Nuit',
        phone: '0901234567',
        zipCode: '75009',
        city: 'Paris',
        role: Role.PROMOTER,
        status: Status.ACTIVE,
        isVerifyEmail: true,
        name: 'Sophie Club',
        website: 'https://sophie-club.fr',
        establishmentType: EstablishmentType.CLUB,
        retaurantAddress: '22 rue de la Nuit',
        restaurantPhone: '0901234567',
        restaurantEmail: 'club.sophie@mail.fr',
      },
      {
        alias: 'paul-pub',
        email: 'paul-pub@mail.fr',
        firstName: 'Paul',
        lastName: 'Pub',
        description:
          'Pub avec une ambiance conviviale et des soirées quiz hebdomadaires.',
        capacity: 130,
        address: '35 rue de la Convivialité',
        phone: '0123456780',
        zipCode: '69004',
        city: 'Lyon 4e',
        role: Role.PROMOTER,
        status: Status.ACTIVE,
        isVerifyEmail: true,
        name: 'Paul Pub',
        website: 'https://paul-pub.fr',
        establishmentType: EstablishmentType.PUB,
        retaurantAddress: '35 rue de la Convivialité',
        restaurantPhone: '0123456780',
        restaurantEmail: 'pub.paul@mail.fr',
      },
    ];

    for (const fakeEstablishment of fakeEstablishments) {
      const user = await queryRunner.manager.save(
        queryRunner.manager.create(User, {
          alias: fakeEstablishment.alias,
          email: fakeEstablishment.email,
          firstName: fakeEstablishment.firstName,
          lastName: fakeEstablishment.lastName,
          // ggignore: ignore this secret
          password: 'MegaPassword123',
          phone: fakeEstablishment.phone,
          address: fakeEstablishment.address,
          zipCode: fakeEstablishment.zipCode,
          city: fakeEstablishment.city,
          role: fakeEstablishment.role,
          status: fakeEstablishment.status,
          isVerifyEmail: fakeEstablishment.isVerifyEmail,
        }),
      );

      await queryRunner.manager.save(
        queryRunner.manager.create(EstablishmentProfile, {
          user: user,
          name: fakeEstablishment.name,
          description: fakeEstablishment.description,
          capacity: fakeEstablishment.capacity,
          address: fakeEstablishment.retaurantAddress,
          phone: fakeEstablishment.restaurantPhone,
          email: fakeEstablishment.restaurantEmail,
          website: fakeEstablishment.website,
          type: fakeEstablishment.establishmentType,
          zipCode: 69001,
          city: 'Lyon 1',
        }),
      );
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.manager.delete(User, { role: Role.PROMOTER });
  }
}
